export {default as Homepage} from './Homepage'
export {default as About} from './About'
export {default as Skills} from './Skills'
export {default as Projects} from './Projects'
export {default as Contact} from './Contact'
export {default as Services} from './Services'